Traceback (most recent call last):
  File "/home/mfvargas/miniconda3/envs/curso-python-imn/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/mfvargas/miniconda3/envs/curso-python-imn/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mfvargas/miniconda3/envs/curso-python-imn/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/mfvargas/miniconda3/envs/curso-python-imn/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/home/mfvargas/miniconda3/envs/curso-python-imn/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/mfvargas/miniconda3/envs/curso-python-imn/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/mfvargas/miniconda3/envs/curso-python-imn/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/mfvargas/miniconda3/envs/curso-python-imn/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# ValidaciÃ³n de entrada de datos
numero = -1
while not(numero >= 5 and numero <= 10) :
    numero = float(input("\nPor favor ingrese un nÃºmero entre 5 y 10: "))
    if not(numero >= 5 and numero <= 10) :
        print("El nÃºmero no estÃ¡ entre 5 y 10, por favor intÃ©ntelo de nuevo...")
print("Â¡Gracias!")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
[0;32m/tmp/ipykernel_2999616/1432823000.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0mnumero[0m [0;34m=[0m [0;34m-[0m[0;36m1[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mwhile[0m [0;32mnot[0m[0;34m([0m[0mnumero[0m [0;34m>=[0m [0;36m5[0m [0;32mand[0m [0mnumero[0m [0;34m<=[0m [0;36m10[0m[0;34m)[0m [0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m     [0mnumero[0m [0;34m=[0m [0mfloat[0m[0;34m([0m[0minput[0m[0;34m([0m[0;34m"\nPor favor ingrese un nÃºmero entre 5 y 10: "[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m     [0;32mif[0m [0;32mnot[0m[0;34m([0m[0mnumero[0m [0;34m>=[0m [0;36m5[0m [0;32mand[0m [0mnumero[0m [0;34m<=[0m [0;36m10[0m[0;34m)[0m [0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m         [0mprint[0m[0;34m([0m[0;34m"El nÃºmero no estÃ¡ entre 5 y 10, por favor intÃ©ntelo de nuevo..."[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniconda3/envs/curso-python-imn/lib/python3.9/site-packages/ipykernel/kernelbase.py[0m in [0;36mraw_input[0;34m(self, prompt)[0m
[1;32m   1001[0m         """
[1;32m   1002[0m         [0;32mif[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0m_allow_stdin[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1003[0;31m             raise StdinNotImplementedError(
[0m[1;32m   1004[0m                 [0;34m"raw_input was called, but this frontend does not support input requests."[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1005[0m             )

[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

